// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMztg8MN8E6Lbbi6gejb3A4whULkFMUgY',
    appId: '1:635995796421:android:e98032f13cd97997e6d1ac',
    messagingSenderId: '635995796421',
    projectId: 'allin-d0e2d',
    storageBucket: 'allin-d0e2d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmgQY02h8CQjBHocLh6id9Ps76fwilmg0',
    appId: '1:635995796421:ios:1d156c9ff34066ace6d1ac',
    messagingSenderId: '635995796421',
    projectId: 'allin-d0e2d',
    storageBucket: 'allin-d0e2d.firebasestorage.app',
    iosBundleId: 'com.yourcompany.allin',
    databaseURL: 'https://allin-d0e2d-default-rtdb.firebaseio.com', // CRITICAL: Required for game rooms
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQLdsCCxnMyTb7oMU0myhXMrmPRcD2l8Q',
    appId: '1:635995796421:web:91217e49d3093a4fe6d1ac',
    messagingSenderId: '635995796421',
    projectId: 'allin-d0e2d',
    authDomain: 'allin-d0e2d.firebaseapp.com',
    storageBucket: 'allin-d0e2d.firebasestorage.app',
    measurementId: 'G-5XNCEMCQMF',
    databaseURL: 'https://allin-d0e2d-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQLdsCCxnMyTb7oMU0myhXMrmPRcD2l8Q',
    appId: '1:635995796421:web:91217e49d3093a4fe6d1ac',
    messagingSenderId: '635995796421',
    projectId: 'allin-d0e2d',
    authDomain: 'allin-d0e2d.firebaseapp.com',
    storageBucket: 'allin-d0e2d.firebasestorage.app',
    measurementId: 'G-5XNCEMCQMF',
  );
}
